RealEstate.UI.Layer/Controllers/Admin/AdminConsultantController.cs
using FluentValidation.Results;
using RealEstate.BusinessLayer.Concrate;
using RealEstate.BusinessLayer.ValidationRules;
using RealEstate.DataAccessLayer.EntitiyFramework;
using RealEstate.EntityLayer.Concrete;
using RealEstate.UI.Layer.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RealEstate.UI.Layer.Controllers.Admin
{
    public class AdminConsultantController : Controller
    {
        ConsultantManager consultantManager = new ConsultantManager(new EfConsultantDAL());

        public ActionResult Index()
        {
            var consultant = new RealEstateViewModel()
            {
                Consultant = consultantManager.GetList()
            };
            return View(consultant);
        }

        [HttpGet]
        public ActionResult AddConsultant()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddConsultant(TBL_REALESTATE_CONSULTANT p)
        {
            ConsultantValidator c_validation = new ConsultantValidator();
            ValidationResult result = c_validation.Validate(p);

            if (result.IsValid)
            {
                consultantManager.Insert(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                
            }

            return View();

        }


        [HttpGet]
        public ActionResult UpdateConsultant(int id)
        {
            var consultant = consultantManager.GetByID(id);
            return View(consultant);
        }


        [HttpPost]
        public ActionResult UpdateConsultant(TBL_REALESTATE_CONSULTANT p)
        {
            ConsultantValidator c_validation = new ConsultantValidator();
            ValidationResult result = c_validation.Validate(p);

            if (result.IsValid)
            {
                consultantManager.Update(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

            }
            return View();
        }



        public ActionResult GetProfile(int id)
        {

            var getprofile = new RealEstateViewModel
            {
                Consultant_GetID = consultantManager.GetByID(id)
            }; 

            return View(getprofile);

        }





    }
}

RealEstate.UI.Layer/Views/AdminConsultant/AddConsultant.cshtml
@model RealEstate.EntityLayer.Concrete.TBL_REALESTATE_CONSULTANT

@{
    ViewBag.Title = "AddConsultant";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<section class="content">

    @using (Html.BeginForm("AddConsultant", "AdminConsultant", FormMethod.Post))
    {
        <div class="card-body">
            <div class="form-group">
                <label for="inputName">Adı</label>
                @Html.TextBoxFor(x => x.NAME, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NAME, "", new { style = "color:red;" })


                <label for="inputDescription">Soyadı</label>
                @Html.TextBoxFor(x => x.SURNAME, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.SURNAME, "", new { style = "color:red;" })



                <label for="inputStatus">Telefon</label>
                @Html.TextBoxFor(x => x.PHONE, new { @class = "form-control", @type = "tel" })
                @Html.ValidationMessageFor(x => x.PHONE, "", new { style = "color:red;" })



                <label for="inputStatus">E-Mail</label>
                @Html.TextBoxFor(x => x.EMAIL, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.EMAIL, "", new { style = "color:red;" })


                <label for="inputStatus">Hakkında</label>
                @Html.TextAreaFor(x => x.DETAIL, new { @class = "form-control", @rows = "4" })
                @Html.ValidationMessageFor(x => x.DETAIL, "", new { style = "color:red;" })


                <label for="inputStatus">Uzmanlık</label>
                @Html.TextBoxFor(x => x.SPECIALIZATION, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.SPECIALIZATION, "", new { style = "color:red;" })


                <label for="inputStatus">Fotoğraf</label>
                @Html.TextBoxFor(x => x.IMAGE, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.IMAGE, "", new { style = "color:red;" })

            </div>

            <button class="btn btn-success">
                Ekle
            </button>

        </div>

    }



</section>

RealEstate.UI.Layer/Views/AdminConsultant/Index.cshtml
@model RealEstate.UI.Layer.ViewModel.RealEstateViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@*Danışman Index Sayfası*@
<section class="content">
    <div class="card card-solid">
        <div class="card-body pb-0">
            <div class="row d-flex align-items-stretch">
                @foreach (var i in Model.Consultant)
                {
                <div class="col-12 col-sm-6 col-md-4  align-items-stretch">
                    <div class="card bg-light">
                        <div class="card-header text-muted border-bottom-0">
                            Danışman
                        </div>
                        <div class="card-body pt-0">
                            <div class="row">
                                <div class="col-7">
                                    <h2 class="lead"><b>@i.NAME @i.SURNAME</b></h2>
                                    <p class="text-muted text-sm"><b>Uzmanlık: </b> @i.SPECIALIZATION </p>
                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> E-Mail : @i.EMAIL</li>
                                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Telefon : + 90 @i.PHONE </li>
                                    </ul>
                                </div>
                                <div class="col-5 text-center">
                                    <img src="../../dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="text-right">
                                <a href="/AdminConsultant/GetProfile/@i.ID" class="btn btn-sm bg-teal">
                                    <i class="fas fa-comments"></i>Profili Göster
                                </a>
                                <a href="/AdminConsultant/UpdateConsultant/@i.ID" class="btn btn-sm btn-primary">
                                    <i class="fas fa-user"></i> Profili Düzenle
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        <nav aria-label="Contacts Page Navigation">
            <ul class="pagination justify-content-center m-0">
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">4</a></li>
                <li class="page-item"><a class="page-link" href="#">5</a></li>
                <li class="page-item"><a class="page-link" href="#">6</a></li>
                <li class="page-item"><a class="page-link" href="#">7</a></li>
                <li class="page-item"><a class="page-link" href="#">8</a></li>
            </ul>
        </nav>
    </div>
    <!-- /.card-footer -->
    <!-- /.card -->

</section>









@*Silme kısmı eklenecek*@

RealEstate.UI.Layer/Views/AdminConsultant/UpdateConsultant.cshtml
@model RealEstate.EntityLayer.Concrete.TBL_REALESTATE_CONSULTANT

@{
    ViewBag.Title = "UpdateConsultant";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<section class="content">

    @using (Html.BeginForm("UpdateConsultant", "AdminConsultant", FormMethod.Post))
    {
        <div class="card-body">
            <div class="form-group">
                <label for="inputName">Adı</label>
                @Html.TextBoxFor(x => x.NAME, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NAME, "", new { style = "color:red;" })


                <label for="inputDescription">Soyadı</label>
                @Html.TextBoxFor(x => x.SURNAME, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.SURNAME, "", new { style = "color:red;" })



                <label for="inputStatus">Telefon</label>
                @Html.TextBoxFor(x => x.PHONE, new { @class = "form-control", @type = "tel" })
                @Html.ValidationMessageFor(x => x.PHONE, "", new { style = "color:red;" })



                <label for="inputStatus">E-Mail</label>
                @Html.TextBoxFor(x => x.EMAIL, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.EMAIL, "", new { style = "color:red;" })


                <label for="inputStatus">Hakkında</label>
                @Html.TextAreaFor(x => x.DETAIL, new { @class = "form-control", @row = "4" })
                @Html.ValidationMessageFor(x => x.DETAIL, "", new { style = "color:red;" })


                <label for="inputStatus">Uzmanlık</label>
                @Html.TextBoxFor(x => x.SPECIALIZATION, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.SPECIALIZATION, "", new { style = "color:red;" })


                <label for="inputStatus">Fotoğraf</label>
                @Html.TextBoxFor(x => x.IMAGE, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.IMAGE, "", new { style = "color:red;" })

            </div>

            <button class="btn btn-success">
                Kaydet
            </button>

        </div>

    }
    @Html.HiddenFor(x => x.ID)


</section>