RealEstate.UI.Layer/Controllers/Admin/AdminCustomerController.cs
using FluentValidation.Results;
using RealEstate.BusinessLayer.Concrate;
using RealEstate.BusinessLayer.ValidationRules;
using RealEstate.DataAccessLayer.EntitiyFramework;
using RealEstate.EntityLayer.Concrete;
using RealEstate.UI.Layer.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RealEstate.UI.Layer.Controllers.Admin
{
    public class AdminCustomerController : Controller
    {
        CustomerManager cm = new CustomerManager(new EfCustomerDAL());
      
        public ActionResult Index()
        {
            var customer = new RealEstateViewModel
            {
                Customers = cm.GetList()
            };

            return View(customer);
        }


        [HttpGet]
        public ActionResult AddCustomer()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AddCustomer(TBL_CUSTOMER p)
        {
            CustomerValidation c_validation = new CustomerValidation();
            ValidationResult result = c_validation.Validate(p);

            if (result.IsValid)
            {
                cm.Insert(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

            }
            return View();

        }



        [HttpGet]
        public ActionResult UpdateCustomer(int id)
        {
            var customer = cm.GetByID(id);
            return View(customer);
        }


        [HttpPost]
        public ActionResult UpdateCustomer(TBL_CUSTOMER p)
        {
            CustomerValidation c_validation = new CustomerValidation();
            ValidationResult result = c_validation.Validate(p);

            if (result.IsValid)
            {
                cm.Update(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }

            }

            return View();
        }

        public ActionResult DeleteCustomer(int id)
        {
            var customer = cm.GetByID(id);
            cm.Delete(customer);
            return RedirectToAction("Index");
        }








    }
}

RealEstate.UI.Layer/Views/AdminCustomer/AddCustomer.cshtml
@model RealEstate.EntityLayer.Concrete.TBL_CUSTOMER
@{
    ViewBag.Title = "AddCustomer";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">

    @using (Html.BeginForm("AddCustomer", "AdminCustomer", FormMethod.Post))
    {
        <div class="card-body">
            <div class="form-group">
                <label for="inputName">Adı</label>
                @Html.TextBoxFor(x=>x.CUSTOMER_NAME, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CUSTOMER_NAME, "", new { style = "color:red;" })


                <label for="inputDescription">Soyadı</label>
                @Html.TextBoxFor(x => x.CUSTOMER_SURNAME, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CUSTOMER_SURNAME, "", new { style = "color:red;" })



                <label for="inputStatus">Telefon</label>
                @Html.TextBoxFor(x => x.CUSTOMER_PHONE, new { @class = "form-control", @type = "tel" })
                @Html.ValidationMessageFor(x => x.CUSTOMER_PHONE, "", new { style = "color:red;" })



                <label for="inputStatus">E-Mail</label>
                @Html.TextBoxFor(x => x.CUSTOMER_MAIL, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CUSTOMER_MAIL, "", new { style = "color:red;" })


                

            </div>

            <button class="btn btn-success">
                Ekle
            </button>

        </div>

    }



</section>

RealEstate.UI.Layer/Views/AdminCustomer/Index.cshtml
@model RealEstate.UI.Layer.ViewModel.RealEstateViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">

<!-- Default box -->
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Müşteriler</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i>
            </button>
        </div>
    </div>
    <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
                <tr>
                    <th style="width: 1%">
                        ID
                    </th>
                    <th style="width: 20%">
                        Adı
                    </th>
                    <th style="width: 30%">
                        Soyadı
                    </th>
                    <th>
                        E-Mail
                    </th>
                    <th style="width: 8%" class="text-center">
                        Telefon
                    </th>
                    <th style="width: 20%">
                    </th>
                </tr>
            </thead>
            @foreach(var i in Model.Customers)
            {

                <tbody>
                    <tr>
                        <td>
                            @i.CUSTOMER_ID
                        </td>
                        <td>                           
                                @i.CUSTOMER_NAME                                      
                        </td>
                        <td>
                            @i.CUSTOMER_SURNAME
                        </td>
                        <td>
                            @i.CUSTOMER_MAIL
                        </td>
                        <td>
                            @i.CUSTOMER_PHONE
                        </td>


                        <td class="project-actions text-right">
                            <a class="btn btn-primary btn-sm" href="#">
                                <i class="fas fa-folder">
                                </i>
                                Görünüm
                            </a>
                            <a class="btn btn-info btn-sm" href="/AdminCustomer/UpdateCustomer/@i.CUSTOMER_ID">
                                <i class="fas fa-pencil-alt">
                                </i>
                                Düzenle
                            </a>
                            <a class="btn btn-danger btn-sm" href="/AdminCustomer/DeleteCustomer/@i.CUSTOMER_ID">
                                <i class="fas fa-trash">
                                </i>
                                Sil
                            </a>
                        </td>
                    </tr>
                </tbody>
            }
        </table>
    </div>
    <br />
    <button class="btn btn-success" onclick="window.location.href='/AdminCustomer/AddCustomer'">
        Yeni Müşteri Ekle
    </button>


    <!-- /.card-body -->
</div>
<!-- /.card -->
</section>

RealEstate.UI.Layer/Views/AdminCustomer/UpdateCustomer.cshtml
@model RealEstate.EntityLayer.Concrete.TBL_CUSTOMER

@{
    ViewBag.Title = "UpdateCustomer";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<section class="content">

    @using (Html.BeginForm("UpdateCustomer", "AdminCustomer", FormMethod.Post))
    {
        <div class="card-body">
            <div class="form-group">
                <label for="inputName">Adı</label>
                @Html.TextBoxFor(x => x.CUSTOMER_NAME, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CUSTOMER_NAME, "", new { style = "color:red;" })


                <label for="inputDescription">Soyadı</label>
                @Html.TextBoxFor(x => x.CUSTOMER_SURNAME, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CUSTOMER_SURNAME, "", new { style = "color:red;" })



                <label for="inputStatus">Telefon</label>
                @Html.TextBoxFor(x => x.CUSTOMER_PHONE, new { @class = "form-control", @type = "tel" })
                @Html.ValidationMessageFor(x => x.CUSTOMER_PHONE, "", new { style = "color:red;" })



                <label for="inputStatus">E-Mail</label>
                @Html.TextBoxFor(x => x.CUSTOMER_MAIL, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CUSTOMER_MAIL, "", new { style = "color:red;" })




            </div>

            <button class="btn btn-success">
                Kaydet
            </button>

        </div>
        @Html.HiddenFor(x => x.CUSTOMER_ID)
    }



</section>