RealEstate.UI.Layer/Controllers/BuyController.cs
using RealEstate.BusinessLayer.Concrate;
using RealEstate.DataAccessLayer.EntitiyFramework;
using RealEstate.EntityLayer.Concrete;
using RealEstate.UI.Layer.EntitiyFramework;
using RealEstate.UI.Layer.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RealEstate.UI.Layer.Controllers
{
    public class BuyController : Controller
    {

        ProductManager productManager = new ProductManager(new EfProductDAL());
        Product_FeatureManager featureManager = new Product_FeatureManager(new EfProductFeatureDAL());


        public ActionResult Index()
        {

            var viewmodel = new RealEstateViewModel
            {
                Products = productManager.GetTypeProduct(2),
                Product_Features = featureManager.GetList()
            };

            return View(viewmodel);
        }

        


    }
}

RealEstate.UI.Layer/Controllers/ContactController.cs
using RealEstate.BusinessLayer.Concrate;
using RealEstate.DataAccessLayer.EntitiyFramework;
using RealEstate.EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RealEstate.UI.Layer.Controllers
{
    public class ContactController : Controller
    {
        
        ContactManager contactManager = new ContactManager(new EfContactDAL());


        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ContactPush(TBL_CONTACT p)
        {
            p.DATE = DateTime.Parse(DateTime.Now.ToShortDateString());
            contactManager.Insert(p);
            return RedirectToAction("Index", "Home");
        }


    }
}

RealEstate.UI.Layer/Controllers/ProductsController.cs
using RealEstate.BusinessLayer.Concrate;
using RealEstate.DataAccessLayer.EntitiyFramework;
using RealEstate.EntityLayer.Concrete;
using RealEstate.UI.Layer.EntitiyFramework;
using RealEstate.UI.Layer.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RealEstate.UI.Layer.Controllers
{
    public class ProductsController : Controller
    {

        ProductManager productManager = new ProductManager(new EfProductDAL());
        Product_FeatureManager product_Feature = new Product_FeatureManager(new EfProductFeatureDAL());


        public ActionResult Index()
        {
            
            var viewmodel = new RealEstateViewModel
            {
                Products = ProductGet(),
                Product_Features =ProductGetFeatures()

            };
            return View(viewmodel);
        }


        private List<TBL_PRODUCT> ProductGet()
        {
            return productManager.GetList();
        }

        private List<TBL_PRODUCT_FEATURES> ProductGetFeatures()
        {
            return product_Feature.GetList();
        }





    }
}

RealEstate.UI.Layer/Controllers/RentController.cs
using RealEstate.BusinessLayer.Concrate;
using RealEstate.DataAccessLayer.EntitiyFramework;
using RealEstate.EntityLayer.Concrete;
using RealEstate.UI.Layer.EntitiyFramework;
using RealEstate.UI.Layer.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RealEstate.UI.Layer.Controllers
{
    public class RentController : Controller
    {
        ProductManager productManager = new ProductManager(new EfProductDAL());
        Product_FeatureManager product_Feature = new Product_FeatureManager(new EfProductFeatureDAL());

        public ActionResult Index()
        {
            var viewmodel = new RealEstateViewModel
            {
                Products = productManager.GetTypeProduct(1),
                Product_Features = ProductFeature()
            };
            return View(viewmodel);
        }
       
        private List<TBL_PRODUCT_FEATURES> ProductFeature()
        {
            return  product_Feature.GetList();
        }
        


    }
}

RealEstate.UI.Layer/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html class="no-js">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Estate &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />


    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
    <!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'> -->
    <!-- Animate.css -->
    <link href="~/Content/TemplateCSS/animate.css" rel="stylesheet" />

    <!-- Icomoon Icon Fonts-->
    <link href="~/Content/TemplateCSS/icomoon.css" rel="stylesheet" />

    <!-- Bootstrap  -->
    <link href="~/Content/TemplateCSS/bootstrap.css" rel="stylesheet" />

    <!-- Flexslider  -->
    <link href="~/Content/TemplateCSS/flexslider.css" rel="stylesheet" />

    <!-- Theme style  -->
    <link href="~/Content/sass/style.css" rel="stylesheet" />

    <!-- Modernizr JS -->
    <script src="~/Content/TemplateJS/modernizr-2.6.2.min.js"></script>


</head>
<body>
    <div id="fh5co-page">
        <header id="fh5co-header" role="banner">
            <div class="container">
                <div class="row">
                    <div class="header-inner">
                        <h1><a href="@Url.Action("Index","Home")">GAYRİMENKUL<span>.</span></a></h1>
                        <nav role="navigation">
                            <ul>
                                <li><a href="@Url.Action("Index","Buy")">Satılık</a></li>
                                <li><a href="@Url.Action("Index","Rent")">Kiralık</a></li>
                                <li><a href="@Url.Action("Index","Products")">Tüm İlanlar</a></li>
                                <li class="cta"><a href="@Url.Action("Index","Contact")">İletişime Geç</a></li>
                                <li class="cta"><a href="contact.html">Kayıt Ol</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </header>

        <!-- Ana sayfa slider kısmı -->
        @RenderBody()

    </div>

    <!--Footer-->
    <footer id="fh5co-footer" role="contentinfo">

        <div class="container">
            <div class="row">

                <div class="col-md-3 col-sm-12 col-xs-12">
                    <h3>Hakkımızda</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lorem magna, vehicula at lorem nec, posuere semper libero. Maecenas sed diam eget risus porta condimentum.</p>
                    <p><a href="#" class="btn btn-primary btn-outline with-arrow btn-sm">Daha Fazla Bilgi <i class="icon-arrow-right"></i></a></p>
                </div>

                <div class="col-md-6 col-sm-12">
                    <h3> hizmetlerimiz</h3>
                    <ul class="float">
                        <li><a href="#">Web Tasarım</a></li>
                        <li><a href="#">Branding & Kimlik</a></li>
                        <li><a href="#">Ücretsiz HTML5 Şablonları</a></li>
                        <li><a href="#">El Yapımı Şablonlar</a></li>
                    </ul>
                </div>

                <div class="col-md-3 col-sm-12">
                    <h3>Bizi Takip Edin</h3>
                    <ul class="fh5co-social">
                        <li><a href="#"><i class="icon-twitter"></i></a></li>
                        <li><a href="#"><i class="icon-facebook"></i></a></li>
                        <li><a href="#"><i class="icon-google-plus"></i></a></li>
                        <li><a href="#"><i class="icon-instagram"></i></a></li>
                    </ul>
                </div>

            </div>

            <div class="col-md-12 fh5co-copyright text-center">
                <p>&copy; <?php echo date("Y"); ?> Emlak Firması. Tüm Hakları Saklıdır. <span>Tasarım & <i class="icon-heart"></i> <a href="#">Emlak Firması</a> | Demo Görselleri <a href="https://unsplash.com/" target="_blank">Unsplash</a></span></p>
            </div>

        </div>
    </footer>
     


    <!-- jQuery -->
    <script src="~/Content/TemplateJS/jquery.min.js"></script>

    <!-- jQuery Easing -->
    <script src="~/Content/TemplateJS/jquery.easing.1.3.js"></script>

    <!-- Bootstrap -->
    <script src="~/Content/TemplateJS/bootstrap.min.js"></script>

    <!-- Waypoints -->
    <script src="~/Content/TemplateJS/jquery.waypoints.min.js"></script>

    <!-- Flexslider -->
    <script src="~/Content/TemplateJS/jquery.flexslider-min.js"></script>


    <!-- MAIN JS -->
    <script src="~/Content/TemplateJS/main.js"></script>


</body>
</html>