RealEstate.UI.Layer/Controllers/Admin/AdminCategoryController.cs
using FluentValidation.Results;
using RealEstate.BusinessLayer.Concrate;
using RealEstate.BusinessLayer.ValidationRules;
using RealEstate.DataAccessLayer.EntitiyFramework;
using RealEstate.EntityLayer.Concrete;
using RealEstate.UI.Layer.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RealEstate.UI.Layer.Controllers.Admin
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDAL());
        
        public ActionResult Index()
        {
            var category = new RealEstateViewModel
            {
                Categories = cm.GetList()
            };


            return View(category);
        }
         
        [HttpGet]
        public ActionResult AddCategory()
        {
            

            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(TBL_CATEGORY p)
        {
            CategoryValidator category_calidator = new CategoryValidator();
            ValidationResult result = category_calidator.Validate(p);

            if(result.IsValid)
            {
                cm.Insert(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = cm.GetByID(id);
            cm.Delete(categoryValue);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
            var categoryValue = cm.GetByID(id);           
            return View(categoryValue);
        }

        [HttpPost]
        public ActionResult UpdateCategory(TBL_CATEGORY p)
        {
            cm.Update(p);
            return RedirectToAction("Index");

        }

        




    }
}

RealEstate.UI.Layer/Views/AdminCategory/AddCategory.cshtml
@model RealEstate.EntityLayer.Concrete.TBL_CATEGORY

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">

    @using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
    {

        
        <div class="card-body">
            <div class="form-group">
                <label for="inputName">Kategori Adı</label>
                <input type="text" class="form-control" name="CATEGORY_NAME">
                @Html.ValidationMessageFor(x=>x.CATEGORY_NAME,"",new {style = "color:red;"})
                
            </div>

            <div class="form-group">
                <label for="inputDescription">Kategori Açıklaması</label>
                <textarea name="CATEGORY_DETAILS" class="form-control" rows="4"></textarea>
                @Html.ValidationMessageFor(x => x.CATEGORY_DETAILS, "", new {style="color:red;"})
            </div>

            <div class="form-group">
                <label for="inputStatus">Durum</label>
                <select name="CATEGORY_STATUS" class="form-control">
                    <option value="">Seçiniz</option>
                    <option value="True">Aktif</option>
                    <option value="False">Pasif</option>
                </select>
                @Html.ValidationMessageFor(x => x.CATEGORY_STATUS, "", new { style = "color:red;" })
            </div>

            <button class="btn btn-success">
                Kaydet
            </button>

        </div>

    }
    


</section>

RealEstate.UI.Layer/Views/AdminCategory/Index.cshtml
@using RealEstate.EntityLayer.Concrete
@model RealEstate.UI.Layer.ViewModel.RealEstateViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">KATEGORİLER</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            ID
                        </th>
                        <th style="width: 20%">
                            Adı
                        </th>
                        <th style="width: 30%">
                            Detaylar
                        </th>
                        <th>
                            Toplam Ürün
                        </th>
                        <th style="width: 8%" class="text-center">
                            Durum
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                </thead>
                @foreach (var i in Model.Categories)
                {

                    <tbody>
                        <tr>
                            <td>
                                @i.CATEGORY_ID
                            </td>
                            <td>
                                <a>
                                    @i.CATEGORY_NAME
                                </a>
                                <br />

                            </td>
                            <td>
                                @i.CATEGORY_DETAILS
                            </td>
                            <td>
                            </td>

                            <td class="project-state">
                                @if (i.CATEGORY_STATUS)
                                {
                                    <span class="badge badge-success">Aktif</span>
                                }
                                else
                                {
                                    <span class="badge badge-danger">Pasif</span>
                                }

                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="#">
                                    <i class="fas fa-folder">
                                    </i>
                                    Görünüm
                                </a>
                                <a class="btn btn-info btn-sm" href="/AdminCategory/UpdateCategory/@i.CATEGORY_ID">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="btn btn-danger btn-sm" href="/AdminCategory/DeleteCategory/@i.CATEGORY_ID">
                                    <i class="fas fa-trash">
                                    </i>
                                    Sil
                                </a>
                            </td>
                        </tr>
                    </tbody>
                }
            </table>
        </div>
        <br />
        <button class="btn btn-success" onclick="window.location.href='/AdminCategory/AddCategory'">
            Yeni Kategori Ekle
        </button>
        
        
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

RealEstate.UI.Layer/Views/AdminCategory/UpdateCategory.cshtml
@model RealEstate.EntityLayer.Concrete.TBL_CATEGORY

@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<section class="content">

    @using (Html.BeginForm("UpdateCategory", "AdminCategory", FormMethod.Post))
    {
        <div class="card-body">
            <div class="form-group">
                <label for="inputName">Kategori Adı</label>
                <input type="text" class="form-control" name="CATEGORY_NAME" value="@Model.CATEGORY_NAME">
                @Html.ValidationMessageFor(x => x.CATEGORY_NAME, "", new { style = "color:red;" })

            </div>

            <div class="form-group">
                <label for="inputDescription">Kategori Açıklaması</label>
                <textarea name="CATEGORY_DETAILS" class="form-control" rows="4">@Model.CATEGORY_DETAILS</textarea>
                @Html.ValidationMessageFor(x => x.CATEGORY_DETAILS, "", new { style = "color:red;" })
            </div>

            <div class="form-group">
                <label for="inputStatus">Durum</label>
                <input type="text" name="CATEGORY_STATUS" class="form-control" value="@(Model.CATEGORY_STATUS==true?"Aktif":"Pasif")">
                @Html.ValidationMessageFor(x => x.CATEGORY_STATUS, "", new { style = "color:red;" })
                @*Bu kısımda dropdownlist olması gerekiyor*@
            </div>
            <button class="btn btn-success">
                Güncelle
            </button>

        </div>

        @Html.HiddenFor(x=>x.CATEGORY_ID)

    }



</section>